Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
Traceback (most recent call last):
  File "swarm-sim.py", line 141, in <module>
    swarm_sim(sys.argv[1:])
  File "swarm-sim.py", line 28, in swarm_sim
    create_directory_for_data(config_data, unique_descriptor)
  File "swarm-sim.py", line 113, in create_directory_for_data
    if not os.path.exists(config_data.directory_csv):
AttributeError: 'ConfigData' object has no attribute 'directory_csv'
